services:
  vscode:
    build: .
    image: devcontainer
    volumes:
      - ../pv/.claude:/home/node/.claude
      - ../pv/workspace:/workspace
      # - ../:/workspace-data:ro
      # Docker socket to access Docker server
      # - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory
      # - ~/.ssh:/root/.ssh
      # For Windows without WSL, a copy will be made
      # from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # Shell history persistence
      # - ~/.zsh_history:/root/.zsh_history:z
      # Git config
      # - ~/.gitconfig:/root/.
      - ../pv/.ssh:/home/node/.ssh
      - ../pv/.config/fish:/home/node/.config/fish
    tmpfs:
      - /home/node/.tmp/.claude:size=1g,mode=0700,exec
      - /home/node/.tmp/.claude-jobs:size=4g,mode=0700,exec
      - /tmp:size=16g,mode=1777,exec
    environment:
      - TZ=
      - PYTHONPYCACHEPREFIX=/tmp
    # entrypoint: ["sh", "-c", "while sleep 1000; do :; done"]
    command: ["sh", "-c", "while sleep 1000; do :; done"]
